### PR TITLE
handle launch template latest version in observer

### LINKED ISSUE #61: [BUG] Observer does not resolve $latest version of LaunchTemplate
**Describe the bug**
Observer does not resolve $latest version of LaunchTemplate. This causes infinite cycling if asg is set to $latest rather than a numbered version

**To Reproduce**

Set an ASG version to $latest

**Expected behavior**

Observer resolves the latest LT version before doing a compare

**Screenshots or Logs**

**Kubernetes Cluster Version**
`v1.24.8`

**Cyclops Version**
latest

**Additional context**

### PR DESCRIPTION
**Pull request by Jacobious52**
fixes #61 

- Resolve latest launch template version before comparing
- Test for $latest case
- Fix issue with no logs working from the cloudprovider aws package

### CODE REVIEW

File: pkg/cloudprovider/aws/aws.go [hunk 1]
```diff
@@ -325,9 +347,32 @@ func (a *autoscalingGroups) instanceOutOfDate(instance *autoscaling.Instance) bo
...
+		LaunchTemplateId: aws.String(id),
+		Versions:         aws.StringSlice([]string{launchTemplateLatestVersion}),
+	}
+	out, err := a.ec2Service.DescribeLaunchTemplateVersions(input)
+	if err != nil {
+		return "", err
+	}
+
+	if len(out.LaunchTemplateVersions) == 0 {
+		return "", errors.Wrapf(err, "[ASG ]failed to get latest launch template version %q", id)
```
Comment (vincentportella) [inline pkg/cloudprovider/aws/aws.go:370]: nit: `[ASG] failed`

**Review by awprice — APPROVED** [review]
LGTM

**Review by vcatlassian — APPROVED** [review]
